# Attrition Model building

In [14]:
import pandas as pd
import numpy as np

# pd.set_option('display_columns:max', None)

OptionError: "No such keys(s): 'display_columns:max'"

In [12]:
data = pd.read_csv('attr.csv')
data.sample(10)

id  Age Attrition     BusinessTravel  DailyRate  \
640    641   24        No         Non-Travel       1269   
1068  1069   28       Yes  Travel_Frequently        289   
1169  1170   27        No      Travel_Rarely        486   
1145  1146   36        No      Travel_Rarely        559   
1293  1294   43        No         Non-Travel        343   
98      99   58        No      Travel_Rarely        682   
867    868   50        No  Travel_Frequently       1421   
1102  1103   36        No      Travel_Rarely       1157   
976    977   56        No      Travel_Rarely       1369   
195    196   37        No      Travel_Rarely        290   

                  Department  DistanceFromHome  Education EducationField  \
640   Research & Development                 4          1  Life Sciences   
1068  Research & Development                 2          2        Medical   
1169  Research & Development                 8          3        Medical   
1145  Research & Development                12          4  Life Sciences   
1293  Research & Development                 9          3  Life Sciences   
98                     Sales                10          4        Medical   
867   Research & Development                 2          3        Medical   
1102                   Sales                 2          4  Life Sciences   
976   Research & Development                23          3  Life Sciences   
195   Research & Development                21          3  Life Sciences   

      EmployeeCount  ...  RelationshipSatisfaction  StandardHours  \
640               1  ...                         4             80   
1068              1  ...                         3             80   
1169              1  ...                         1             80   
1145              1  ...                         2             80   
1293              1  ...                         3             80   
98                1  ...                         3             80   
867               1  ...                         3             80   
1102              1  ...                         4             80   
976               1  ...                         1             80   
195               1  ...                         1             80   

     StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
640                 0                  6                      2   
1068                0                  8                      2   
1169                0                  5                      0   
1145                2                  7                      2   
1293                0                  7                      2   
98                  0                 38                      1   
867                 1                 32                      3   
1102                0                  7                      3   
976                 1                 33                      0   
195                 1                  8                      3   

      WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
640                 2              5                   2   
1068                2              0                   0   
1169                3              3                   2   
1145                3              3                   2   
1293                2              3                   2   
98                  2             37                  10   
867                 3              2                   2   
1102                2              3                   2   
976                 3             19                  16   
195                 2              8                   7   

     YearsSinceLastPromotion  YearsWithCurrManager  
640                        3                     4  
1068                       0                     0  
1169                       0                     2  
1145                       1                     1  
1293                       1                     2  
98                         1                

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   id                        1470 non-null   int64 
 1   Age                       1470 non-null   int64 
 2   Attrition                 1470 non-null   object
 3   BusinessTravel            1470 non-null   object
 4   DailyRate                 1470 non-null   int64 
 5   Department                1470 non-null   object
 6   DistanceFromHome          1470 non-null   int64 
 7   Education                 1470 non-null   int64 
 8   EducationField            1470 non-null   object
 9   EmployeeCount             1470 non-null   int64 
 10  EmployeeNumber            1470 non-null   int64 
 11  EnvironmentSatisfaction   1470 non-null   int64 
 12  Gender                    1470 non-null   object
 13  HourlyRate                1470 non-null   int64 
 14  JobInvolvement          

In [13]:
data.describe()

id          Age    DailyRate  DistanceFromHome    Education  \
count  1470.000000  1470.000000  1470.000000       1470.000000  1470.000000   
mean    735.500000    36.923810   802.485714          9.192517     2.912925   
std     424.496761     9.135373   403.509100          8.106864     1.024165   
min       1.000000    18.000000   102.000000          1.000000     1.000000   
25%     368.250000    30.000000   465.000000          2.000000     2.000000   
50%     735.500000    36.000000   802.000000          7.000000     3.000000   
75%    1102.750000    43.000000  1157.000000         14.000000     4.000000   
max    1470.000000    60.000000  1499.000000         29.000000     5.000000   

       EmployeeCount  EmployeeNumber  EnvironmentSatisfaction   HourlyRate  \
count         1470.0     1470.000000              1470.000000  1470.000000   
mean             1.0     1024.865306                 2.721769    65.891156   
std              0.0      602.024335                 1.093082    20.329428   
min              1.0        1.000000                 1.000000    30.000000   
25%              1.0      491.250000                 2.000000    48.000000   
50%              1.0     1020.500000                 3.000000    66.000000   
75%              1.0     1555.750000                 4.000000    83.750000   
max              1.0     2068.000000                 4.000000   100.000000   

       JobInvolvement  ...  RelationshipSatisfaction  StandardHours  \
count     1470.000000  ...               1470.000000         1470.0   
mean         2.729932  ...                  2.712245           80.0   
std          0.711561  ...                  1.081209            0.0   
min          1.000000  ...                  1.000000           80.0   
25%          2.000000  ...                  2.000000           80.0   
50%          3.000000  ...                  3.000000           80.0   
75%          3.000000  ...                  4.000000           80.0   
max          4.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 27 columns]

# EDA

In [16]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Mapping the categorical variables.
# 0 - Travel_Rarely
# 1 - Travel_Frequently
# 2 - Non-Travel
print(f"Unique Values pre-mapping:\n{data.BusinessTravel.unique()}\n")
data['BusinessTravel'] = data['BusinessTravel'].map({'Travel_Rarely' : 0,
                                                     'Travel_Frequently' : 1,
                                                     'Non-Travel' : 2}).astype('int64')
print(f"Unique Values post-mapping:\n{data.BusinessTravel.unique()}")

Unique Values pre-mapping:
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']

Unique Values post-mapping:
[0 1 2]


In [4]:
# 0 - Sales
# 1 - Reasearch & Development
# 2 - Human Resources
print(f"Unique Values pre-mapping:\n{data.Department.unique()}\n")
data['Department'] = data['Department'].map({'Sales' : 0,
                                             'Research & Development' : 1,
                                             'Human Resources' : 2}).astype('int64')
print(f"Unique Values post-mapping:\n{data.Department.unique()}")

Unique Values pre-mapping:
['Sales' 'Research & Development' 'Human Resources']

Unique Values post-mapping:
[0 1 2]


In [5]:
# 0 - Life Sciences
# 1 - Medical
# 2 - Marketing
# 3 - Technical Degree
# 4 - Human Resources
# 5 - Others
print(f"unique values pre-mapping:\n{data.EducationField.unique()}\n")
data['EducationField'] = data['EducationField'].map({'Life Sciences' : 0,
                                                     'Medical' : 1,
                                                     'Marketing' : 2,
                                                     'Technical Degree' : 3,
                                                     'Human Resources' : 4,
                                                     'Other' : 5}).astype('int64')
print(f"unique values post-mapping:\n{data.EducationField.unique()}")

unique values pre-mapping:
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']

unique values post-mapping:
[0 5 1 2 3 4]


In [6]:
# 0 - Male
# 1 - Female
print(f"Unique values pre-mapping:\n{data.Gender.unique()}\n")
data['Gender'] = data['Gender'].map({'Male' : 0,
                                     'Female' : 1}).astype('int64')
print(f"Unique values post-mapping:\n{data.Gender.unique()}")

Unique values pre-mapping:
['Female' 'Male']

Unique values post-mapping:
[1 0]


In [7]:
# 0 - No
# 1 - Yes
print(f"Unique values pre-mapping:\n{data.OverTime.unique()}\n")
data['OverTime'] = data['OverTime'].map({'No' : 0,
                                         'Yes' : 1}).astype('int64')
print(f"Unique values post-mapping:\n{data.OverTime.unique()}")

Unique values pre-mapping:
['Yes' 'No']

Unique values post-mapping:
[1 0]


In [8]:
# 0 - No
# 1 - Yes
print(f"Unique values pre-mapping:\n{data.Attrition.unique()}\n")
data['Attrition'] = data['Attrition'].map({'No' : 0,
                                         'Yes' : 1}).astype('int64')
print(f"Unique values post-mapping:\n{data.Attrition.unique()}")

Unique values pre-mapping:
['Yes' 'No']

Unique values post-mapping:
[1 0]


In [9]:
# 0 - Single
# 1 - Married
# 2 - Divorced
data.MaritalStatus.unique()
print(f"Unique values pre-mapping:\n{data.MaritalStatus.unique()}\n")
data['MaritalStatus'] = data['MaritalStatus'].map({'Single' : 0,
                                                   'Married' : 1,
                                                   'Divorced' : 2}).astype('int64')
print(f"Unique values post-mapping:\n{data.MaritalStatus.unique()}")

Unique values pre-mapping:
['Single' 'Married' 'Divorced']

Unique values post-mapping:
[0 1 2]


In [10]:
# 0 - Sales Executive
# 1 - Research Scientist
# 2 - Laboratory Technician
# 3 - Manufacturing Director
# 4 - Healthcare Representative
# 5 - Manager
# 6 - Sales Representative
# 7 - Research Director
# 8 - Human Resources
data.JobRole.unique()
print(f"Unique values pre-mapping:\n{data.JobRole.unique()}\n")
data['JobRole'] = data['JobRole'].map({'Sales Executive' : 0,
                                       'Research Scientist' : 1,
                                       'Laboratory Technician' : 2,
                                       'Manufacturing Director' : 3,
                                       'Healthcare Representative' : 4,
                                       'Manager' : 5,
                                       'Sales Representative' : 6,
                                       'Research Director' : 7,
                                       'Human Resources' : 8}).astype('int64')
print(f"Unique values post-mapping:\n{data.JobRole.unique()}")

Unique values pre-mapping:
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']

Unique values post-mapping:
[0 1 2 3 4 5 6 7 8]


In [15]:
data.sample(10)

id  Age Attrition     BusinessTravel  DailyRate  \
737    738   41        No      Travel_Rarely        549   
706    707   40       Yes         Non-Travel       1479   
1166  1167   48        No  Travel_Frequently        365   
585    586   23       Yes      Travel_Rarely       1243   
929    930   28        No  Travel_Frequently        193   
117    118   36        No  Travel_Frequently       1467   
1464  1465   26        No      Travel_Rarely       1167   
107    108   25       Yes      Travel_Rarely        240   
390    391   43        No      Travel_Rarely        982   
401    402   56        No  Travel_Frequently        906   

                  Department  DistanceFromHome  Education    EducationField  \
737   Research & Development                 7          2           Medical   
706                    Sales                24          3     Life Sciences   
1166  Research & Development                 4          5           Medical   
585   Research & Development                 6          3     Life Sciences   
929   Research & Development                 2          3     Life Sciences   
117                    Sales                11          2  Technical Degree   
1464                   Sales                 5          3             Other   
107                    Sales                 5          3         Marketing   
390   Research & Development                12          3     Life Sciences   
401                    Sales                 6          3     Life Sciences   

      EmployeeCount  ...  RelationshipSatisfaction  StandardHours  \
737               1  ...                         2             80   
706               1  ...                         4             80   
1166              1  ...                         2             80   
585               1  ...                         3             80   
929               1  ...                         2             80   
117               1  ...                         3             80   
1464              1  ...                         4             80   
107               1  ...                         4             80   
390               1  ...                         3             80   
401               1  ...                         4             80   

     StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
737                 0                  8                      6   
706                 0                 22                      2   
1166                1                 23                      3   
585                 2                  1                      2   
929                 1                  2                      2   
117                 1                 10                      6   
1464                0                  5                      2   
107                 0                  6                      1   
390                 1                 25                      3   
401                 3                 36                      0   

      WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
737                 3              2                   2   
706                 2              1                   0   
1166                3              2                   2   
585                 3              0                   0   
929                 3              2                   2   
117                 3              9                   7   
1464                3              4                   2   
107                 3              6                   4   
390                 3             25                  10   
401                 2              7                   7   

     YearsSinceLastPromotion  YearsWithCurrManager  
737                        2                     1  
706                        0                     0  
1166                       2                     2  
585                        0                     0  
929                        2                     2  
117        

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   id                        1470 non-null   int64 
 1   Age                       1470 non-null   int64 
 2   Attrition                 1470 non-null   int64 
 3   BusinessTravel            1470 non-null   int64 
 4   DailyRate                 1470 non-null   int64 
 5   Department                1470 non-null   int64 
 6   DistanceFromHome          1470 non-null   int64 
 7   Education                 1470 non-null   int64 
 8   EducationField            1470 non-null   int64 
 9   EmployeeCount             1470 non-null   int64 
 10  EmployeeNumber            1470 non-null   int64 
 11  EnvironmentSatisfaction   1470 non-null   int64 
 12  Gender                    1470 non-null   int64 
 13  HourlyRate                1470 non-null   int64 
 14  JobInvolvement          

In [14]:
from scipy import stats

In [45]:
cols = list(data.columns)
remove = ['id', 'Attrition', 'EmployeeCount', 'EmployeeNumber', 'Over18', 'OverTime', 'StandardHours']
cols = [i for i in cols if i not in remove]
cols

for i in range(len(cols)):
    pearson_coef, p_value = stats.pearsonr(data[cols[i]], data['Attrition'])
    print(f"The Pearson Correlation Coefficient of '{cols[i]}' is", pearson_coef," with a P-value of P =", p_value, "\n")

The Pearson Correlation Coefficient of 'Age' is -0.1592050068657796  with a P-value of P = 8.356308021103691e-10 

The Pearson Correlation Coefficient of 'BusinessTravel' is -7.377694602222346e-05  with a P-value of P = 0.9977449860896093 

The Pearson Correlation Coefficient of 'DailyRate' is -0.056651991867629294  with a P-value of P = 0.02985816066026647 

The Pearson Correlation Coefficient of 'Department' is -0.06399059633809041  with a P-value of P = 0.014133018076804602 

The Pearson Correlation Coefficient of 'DistanceFromHome' is 0.07792358295570372  with a P-value of P = 0.0027930600802134964 

The Pearson Correlation Coefficient of 'Education' is -0.03137281964004926  with a P-value of P = 0.2293152033223197 

The Pearson Correlation Coefficient of 'EducationField' is 0.05156704570591765  with a P-value of P = 0.04807060489978447 

The Pearson Correlation Coefficient of 'EnvironmentSatisfaction' is -0.1033689783379361  with a P-value of P = 7.172338549368422e-05 

The Pearso